sudo: required
language: java
services:
- docker
jdk:
- openjdk8
notifications:
  email: false
env:
  global:
  - secure: Sp0yLe43l6uj7lJo6BaF8bb9t8a1X4wXzT3jxIjLI8VSEmMrAGP9TQ6K/XEshQfdn97/e+VRmq1HW9Z1XDskLal8oA9b1fNQqb8vSS5CziWQSFqTr/dAdFoj/4uT+qFEgzXYm76OU92ef0jHyouUqAX5FS0WIiryWt03Nuknvd0BljaGU4fPYINnBFMW+Qi5LFJm9ZH79AQuzxheWeGygboQWpg8g7Gsartn9eFsLTeGYXQMWGQHHL72PJFgi2SSVL8ZHwAmsg8SHub9RpcPvJw0uPxYjbDmtzsFrFePnDHgJvxiFOM7ffpKyrpw1dgGnqZP15ELZrR0JXYBUm9/lODjQH7bQ8l09hKOPGfJnASH1kEz8IcV18yZZkmTf0X+lK4WzCL1hlG5kuf5L1lJdpCNfXD1pKk+rOlY2wior0Ea2h+AHRT1UL49awy2oTMoTUiL8GcS3arhO018/wk0vctck+FpJbsWV4IE71BRESTBahiS7ep3D57lxh/6hIus9JbgMmHs+KRWrHzY/GVO7gmKp1JU1czmYKgFeq1U/OTB8EKQJifylwmzmvi8tkW3D3UG6MSesrEs/7QOEwPuJ2V4l/zLAdNZycBNqeBbJ9v95paPOVlmhbZslCVCssMWefZLKYgbaRbXGHD6ILYsN32WpWmAGB9Qlc+TZXd3Vms=
  - secure: bl+mCl4BMgkjcG85awO9L4Z5SSJ/mQkcDQjWt8hVigE9h4gcigAY/nLAaWMXIFVz83ILO9TjTc+ROfq1C7LHbborQvKrHDhqw01MqaiL+jxrKPzDDchznBrN5Lkn3VVgnNZQY7X0AeHS1/5qt3PovIlAlhzDvQRfn41ogDmy43MH16I2EnKf38xrtbDUSmogxiuCynHzWZFKov7CNIuJ7tRWp6FAwA1CyRerlTxJNWorcBhzE4b4yqWqVSyS0UVHxuzyMKX1q9gXt9N9Td4bxcn74sEA7Y5taiuiac9Jc68Lpv3uPccq+LpzBcpilN1AWj2St7fK74VlKCroP+MIfop+hm588TmD8rIil4ZDXtLAH+px7Kc7wQ869jO3Ilql9TJOriEz/+kcHzoEsQ30eER59eXtToOpT4iWkqO/uo1zcpjRRlUzFM46o/nlMdb5LovJjsbJEwMUk1jjgvAuVCZ/OvEIVr4h3GGr0g5YarmlzJ6vgeqITIJ5ADOgvh3mClrH848a3ssWsP1ItiFaCbK2C9jSVpgiqV5nJYNrTB6ubO/Eas4xpYkTqH6eGtGoT0q7mwGwPplkyxpqOHNoL2KztYCcxwWTfQ4ZtQg3m5DLDV4siRqY0rsZ9IROv4eQdhkZCEWVWDmkNQxcIcm3fAbTGco/t0B7wtKkIsbeSu0=
script: ".travis/build_script.sh"
after_success: ".travis/push_script.sh"
